spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
  #      defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;
    username: sa
    password:

jwt:
  token:
    secret-key: ${SECRET_KEY}
    access-expiration-time: ${ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${REFRESH_EXPIRATION_TIME}

file:
  storage-path: "/Users/lookh/temp/" # use in Integration test (need to change)

firebase:
  key-path: "/Users/lookh/Desktop/gymmi-fcm-firebase-adminsdk.json"
