spring:
  config:
    activate:
      on-profile: dev

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}

  sql:
    init:
      mode: never

jwt:
  token:
    secret-key: ${SECRET_KEY}
    access-expiration-time: ${ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${REFRESH_EXPIRATION_TIME}

file:
  storage-path: ${FILE_STORAGE_PATH}


cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME} # S3 버킷 이름
      path: ${FILE_PATH} # S3에서 이미지 저장에 활용할 기본 경로
    region:
      static: ${REGION} # AWS Region
    stack:
      auto: false
